version: '3.9'

services:
  onlinestatus:
    build:
      context: .
      args:
        SERVER_COMMAND: "npm run server1"
    ports:
      - "8000:8000"

  public-chat:
    build:
      context: .
      args:
        SERVER_COMMAND: "npm run server2"
    ports:
      - "7000:7000"

  roomchat:
    build:
      context: .
      args:
        SERVER_COMMAND: "npm run server3"
    ports:
      - "9000:9000"