version: '3.8'
services:
  main-app:
    build: .
    container_name: Liveunity-Main-Production
    ports:
      - '1000:1000'
    networks:
      - my-shared-network
    # env_file:
    #   - ./server/.env
  roomchat:
    build: ./server/RoomChat
    container_name: Liveunity-Roomchat-Production
    ports:
      - '9000:9000'
    networks:
      - my-shared-network
    depends_on:
      - publicchat
    # env_file:
    #   - ./server/.env
  publicchat:
    build: ./server/PublicChat
    container_name: Liveunity-Public-Chat-Production
    ports:
      - '6000:6000'
    networks:
      - my-shared-network
    depends_on:
      - main-app
    # env_file:
    #   - ./server/.env
networks:
  my-shared-network:
    external: true